# Generated by Django 3.1 on 2020-08-22 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basic Game', max_length=200)),
                ('modifiedBy', models.CharField(max_length=50)),
                ('modifiedDate', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 14, 58, 25, 834154))),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.TimeField(default='00:05:00')),
                ('numTargets', models.IntegerField(default=1)),
                ('modifiedBy', models.CharField(max_length=50)),
                ('modifiedDate', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 14, 58, 25, 834154))),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('TotalGames', models.IntegerField(default=0)),
                ('modifiedBy', models.CharField(max_length=50)),
                ('modifiedDate', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 14, 58, 25, 833156))),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TargetLocation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointValue', models.IntegerField(default=1)),
                ('TargetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.target')),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.game')),
                ('hitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.hit')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.gametype'),
        ),
        migrations.AddField(
            model_name='game',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.player'),
        ),
    ]
