# Generated by Django 3.1 on 2020-08-29 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='modifiedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 21, 12, 23, 633849)),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='duration',
            field=models.IntegerField(default='300'),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='modifiedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 21, 12, 23, 633849)),
        ),
        migrations.AlterField(
            model_name='player',
            name='modifiedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 21, 12, 23, 633849)),
        ),
    ]
